--- 
- 
  hosts: all
  name: "playbook triggered"
  tasks: 
    - name: "Stop and remove the existing running docker"
      docker_container: 
        image: "nikhilgoenka/sample-bank-app:latest"
        name: SampleBankApp
        state: absent
      
    - name: "Deploy the docker with latest code"
      docker_container: 
        image: "nikhilgoenka/sample-bank-app:1.0"
        name: SampleBankApp
        ports: 
          - "3000:3000"
      
    
    - name: "update deployment information"
      uri:
        url: "{{dtdeploymentapiurl}}"
        body_format: json
        method: POST
        body: '{ 
           "eventType": "CUSTOM_DEPLOYMENT", 
           "attachRules": 
             { 
             "tagRule" : 
                [{ 
                   "meTypes" : ["SERVICE"], 
                   "tags" : 
                   [ 
                      { 
                         "context" : "CONTEXTLESS", 
                         "key" : "My_service" 
                      } 
                   ]
                }] },
                "deploymentName":"Deploying the 1.0 build",
                "deploymentVersion":"1.0",
                "remediationAction":"deploy-new-docker.yaml",
                "source":"Ansible",
                "customProperties":
                {
                  "CI Tool": "Ansible Tower",
                  "Current docker version (tag value) ": "latest",
                  "Upgrading to docker version (tag value)": "1.0" 
                } 
             }'
             
    - name: Pause for 1 minutes to build app cache
      pause:
        minutes: 1

    - name: "start load test"
      uri:
        url: "{{dtdeploymentapiurl}}"
        body_format: json
        method: POST
        body: '{ 
           "eventType": "CUSTOM_ANNOTATION", 
           "attachRules": 
             { 
             "tagRule" : 
                [{ 
                   "meTypes" : ["SERVICE"], 
                   "tags" : 
                   [ 
                      { 
                         "context" : "CONTEXTLESS", 
                         "key" : "My_service" 
                      } 
                   ]
                }] },
                "source":"Ansible-playbook",
                "annotationDescription":"Starting load test as part of deployment of new docker image",
                "annotationType":"Notification"
             }'
             
    - name: "Fire requests to verify if the application is working as expected"
      uri:
        url: http://{{my_ip}}:3000/api/users/
        method: GET
      with_sequence: count="50"  
             
    - name: "stop load test"
      uri:
        url: "{{dtdeploymentapiurl}}"
        body_format: json
        method: POST
        body: '{ 
           "eventType": "CUSTOM_ANNOTATION", 
           "attachRules": 
             { 
             "tagRule" : 
                [{ 
                   "meTypes" : ["SERVICE"], 
                   "tags" : 
                   [ 
                      { 
                         "context" : "CONTEXTLESS", 
                         "key" : "My_service" 
                      } 
                   ]
                }] },
                "source":"Ansible-playbook",
                "annotationDescription":"Stopping load test",
                "annotationType":"Notification"
             }'
