---
- name: Print current date
  hosts: all
  tasks:
  - name: Get current date
    command: date
    register: date_result

  - name: Display date
    debug:
      msg: "Current date is {{ date_result.stdout }}"
